services:
  - type: web
    name: energy-efficiency-calculator
    env: node
    buildCommand: npm install && npm run build
    startCommand: npm start
    plan: starter
    envVars:
      - key: NODE_ENV
        value: production
      - key: DATABASE_URL
        fromDatabase:
          name: energy-calculator-db
          property: connectionString

databases:
  - name: energy-calculator-db
    databaseName: energy_calculator
    user: energy_calculator_user
    plan: starter